# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(663, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.BTN_ESCRIBIR = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_ESCRIBIR.setGeometry(QtCore.QRect(180, 220, 93, 28))
        self.BTN_ESCRIBIR.setObjectName("BTN_ESCRIBIR")
        self.BTN_BORRAR = QtWidgets.QPushButton(self.centralwidget)
        self.BTN_BORRAR.setGeometry(QtCore.QRect(400, 220, 93, 28))
        self.BTN_BORRAR.setObjectName("BTN_BORRAR")
        self.LABEL_TEXTO = QtWidgets.QLabel(self.centralwidget)
        self.LABEL_TEXTO.setGeometry(QtCore.QRect(140, 100, 361, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.LABEL_TEXTO.setFont(font)
        self.LABEL_TEXTO.setAlignment(QtCore.Qt.AlignCenter)
        self.LABEL_TEXTO.setObjectName("LABEL_TEXTO")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 663, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BTN_ESCRIBIR.setText(_translate("MainWindow", "Escribir"))
        self.BTN_BORRAR.setText(_translate("MainWindow", "Borrar"))
        self.LABEL_TEXTO.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
